### ISSUE TITLE
Invalid Format. Multiple 400 errors detected. Please wait for 1 minute before trying again.

### ISSUE THREAD

**Issue by JV-X** [circlemind-ai/fast-graphrag#49]
After I changed the model according to the suggestion in this issue（ https://github.com/circlemind-ai/fast-graphrag/issues/48 ）, I ran the following code and got this error. I adjusted the parameters of the embedding model twice, but the result did not change. It seems that there is an error in llm_service, but I don’t know how to fix it. Please give some suggestions

error log:
```
(base) hygx@hygx:~/code/ragflow$  cd /home/hygx/code/ragflow ; /usr/bin/env /home/hygx/code/ragflow/venv/bin/python /home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 48458 -- /home/hygx/code/ragflow/main.py 
Extracting data:   0%|                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Error during information extraction from document: Error code: 418 - {'error_msg': 'Invalid Format. Multiple 400 errors detected. Please wait for 1 minute before trying again.'}
Extracting data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.85s/it]
Error during query: Error code: 418 - {'error_msg': 'Invalid Format. Multiple 400 errors detected. Please wait for 1 minute before trying again.'}
Traceback (most recent call last):
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/instructor/retry.py", line 222, in retry_async
    response: ChatCompletion = await func(*args, **kwargs)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1661, in create
    return await self._post(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1537, in request
    return await self._request(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Error code: 418 - {'error_msg': 'Invalid Format. Multiple 400 errors detected. Please wait for 1 minute before trying again.'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/instructor/retry.py", line 217, in retry_async
    async for attempt in max_retries:
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f7658767910 state=finished raised APIStatusError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/home/hygx/code/ragflow/main.py", line 244, in <module>
    print(grag.query("Who is Scrooge?").response)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_graphrag.py", line 157, in query
    return get_event_loop().run_until_complete(_query())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_graphrag.py", line 153, in _query
    raise e
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_graphrag.py", line 149, in _query
    answer = await self.async_query(query, params)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_graphrag.py", line 175, in async_query
    extracted_entities = await self.information_extraction_service.extract_entities_from_query(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_services/_information_extraction.py", line 47, in extract_entities_from_query
    entities, _ = await format_and_send_prompt(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_llm/_base.py", line 43, in format_and_send_prompt
    return await llm.send_message(prompt=formatted_prompt, response_model=response_model, **args)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_utils.py", line 49, in wait_func
    result = await func(*args, **kwargs)
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/fast_graphrag/_llm/_llm_openai.py", line 90, in send_message
    llm_response: T_model = await self.llm_async_client.chat.completions.create(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/instructor/client.py", line 387, in create
    return await self.create_fn(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/instructor/patch.py", line 161, in new_create_async
    response = await retry_async(
  File "/home/hygx/code/ragflow/venv/lib/python3.10/site-packages/instructor/retry.py", line 248, in retry_async
    raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: Error code: 418 - {'error_msg': 'Invalid Format. Multiple 400 errors detected. Please wait for 1 minute before trying again.'}
```

my code:

```
    
    DOMAIN = "Analyze this story and identify the characters. Focus on how they interact with each other, the locations they explore, and their relationships."

    EXAMPLE_QUERIES = [
        "What is the significance of Christmas Eve in A Christmas Carol?",
        "How does the setting of Victorian London contribute to the story's themes?",
        "Describe the chain of events that leads to Scrooge's transformation.",
        "How does Dickens use the different spirits (Past, Present, and Future) to guide Scrooge?",
        "Why does Dickens choose to divide the story into \"staves\" rather than chapters?"
    ]

    ENTITY_TYPES = ["Character", "Animal", "Place", "Object", "Activity", "Event"]

    grag = GraphRAG(
        working_dir="./book_example",
        domain=DOMAIN,
        example_queries="\n".join(EXAMPLE_QUERIES),
        entity_types=ENTITY_TYPES,
        config=GraphRAG.Config(
        llm_service=OpenAILLMService(model="deepseek-chat", base_url="https://api.deepseek.com/v1", api_key="sk-XXXXX"),
        embedding_service=OpenAIEmbeddingService(
            model="text-embedding-3-small",
            base_url="https://aihubmix.com/v1",
            api_key="sk-XXXXX",
            embedding_dim=512,  # the output embedding dim of the chosen model
        )
    )
    )

    with open("./book.txt") as f:
        grag.insert(f.read())

    print(grag.query("Who is Scrooge?").response)

```

**Comment by liukidar** [comment]
Hello,
this looks like an error within the language model's api call. It seems like the model of your choice ("deepseek-chat") doesn't support the chat interface used by this repo. However without more information about the errors received it is challenging to understand what is exactly the cause of this. Is there some kind of dashboard on deepseek where you can check to see the list of errors?

**Comment by liukidar** [comment]
Hello, if I'm not mistaken, it looks from the other issues that you opened and are now resolved, that this problem was solved. If so could you resolve this issue as completed?

**Comment by JV-X** [comment]
> Hello, if I'm not mistaken, it looks from the other issues that you opened and are now resolved, that this problem was solved. If so could you resolve this issue as completed?

thank you.
