### ISSUE TITLE
during extract，Judge and pop invalid single raw

### ISSUE THREAD

**Issue by shuaidaming** [circlemind-ai/fast-graphrag#53]
★★★ Earlier ensure extract result quality instead of letting it enter embedding pipeline which occur error interrupt due to the super high cost of extract

**Comment by shuaidaming** [comment]
> Hello, what you suggest is perfectly reasonable, however we are relying on pydantic to validate the output of the llm and i'm not sure if it is possible to add a rule like "keep this output if there's at most one error". Something we could do is cache the output for x minutes only if it is a valid output, so when re running the code there would be no need to re evaluate all the correctly sampled chunks. What do you think?

i say whether sig raw data passes validation that must don't interrupt the next embedding pipeline ，not interrupt！no matter which certificate tools such as pydantic ,xx.....，no matter which one you chose。Imagine a scene --- 10billion rows data to build a graphrag but fail because 3 or 5 rows are invalid，you raise the exception which lead to the whole pipeline shut down ，that's very serious， you can save it in some log files then skip this one row ，remove one from 10 billion not affect the whole。  **Absolutely not** raise exception or other any action which can lead to shut down。let whole pipeline run over ，accumulate valid results and skip error not interrupt

**Comment by shuaidaming** [comment]
Building... [upserting graphs]:  14%|█▍        | 1/7 [07:18<43:53, 438.84s/it]

Error during insertion: 1 validation error for TEditRelationList
  Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/json_invalid
Traceback (most recent call last):
  File "D:\python313\Lib\site-packages\instructor\retry.py", line 245, in retry_async
    raise e
  File "D:\python313\Lib\site-packages\instructor\retry.py", line 228, in retry_async
    return await process_response_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "D:\python313\Lib\site-packages\instructor\process_response.py", line 82, in process_response_async
    model = response_model.from_response(
        response,
    ...<2 lines>...
        mode=mode,
    )
  File "D:\python313\Lib\site-packages\instructor\function_calls.py", line 166, in from_response
    return cls.parse_json(completion, validation_context, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\instructor\function_calls.py", line 384, in parse_json
    return cls.model_validate_json(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        message,
        ^^^^^^^^
        context=validation_context,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        strict=strict,
        ^^^^^^^^^^^^^^
    )
    ^
  File "D:\python313\Lib\site-packages\pydantic\main.py", line 656, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for TEditRelationList
  Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/json_invalid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python313\Lib\site-packages\instructor\retry.py", line 217, in retry_async
    async for attempt in max_retries:
    ...<27 lines>...
                raise e
  File "D:\python313\Lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "D:\python313\Lib\site-packages\tenacity\__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14932d475d0 state=finished raised ValidationError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ma_fir\solution_final\2，graphrag推搜.py", line 41, in <module>
    grag.insert(
    ~~~~~~~~~~~^
        b1_z_cont,
        ^^^^^^^^^^
        metadata=b1_z_id,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\python313\Lib\site-packages\fast_graphrag\_graphrag.py", line 75, in insert
    return get_event_loop().run_until_complete(self.async_insert(content, metadata, params, show_progress))
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\python313\Lib\site-packages\fast_graphrag\_graphrag.py", line 143, in async_insert
    raise e
  File "D:\python313\Lib\site-packages\fast_graphrag\_graphrag.py", line 128, in async_insert
    await self.state_manager.upsert(
        llm=self.llm_service, subgraphs=subgraphs, documents=new_chunks_per_data, show_progress=show_progress
    )
  File "D:\python313\Lib\site-packages\fast_graphrag\_services\_state_manager.py", line 120, in upsert
    _, _ = await self.edge_upsert_policy(llm, self.graph_storage, chain(*edges))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\fast_graphrag\_policies\_graph_upsert.py", line 330, in __call__
    tasks = await asyncio.gather(*edge_upsert_tasks)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\fast_graphrag\_policies\_graph_upsert.py", line 223, in _upsert_edge
    upserted_eges, new_edges, to_delete_edges = await self._merge_similar_edges(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        llm, target, existing_edges, edges
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\python313\Lib\site-packages\fast_graphrag\_policies\_graph_upsert.py", line 260, in _merge_similar_edges
    edge_grouping, _ = await format_and_send_prompt(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "D:\python313\Lib\site-packages\fast_graphrag\_llm\_base.py", line 43, in format_and_send_prompt
    return await llm.send_message(prompt=formatted_prompt, response_model=response_model, **args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\fast_graphrag\_utils.py", line 49, in wait_func
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python313\Lib\site-packages\fast_graphrag\_llm\_llm_openai.py", line 90, in send_message
    llm_response: T_model = await self.llm_async_client.chat.completions.create(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "D:\python313\Lib\site-packages\instructor\client.py", line 387, in create
    return await self.create_fn(
           ^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "D:\python313\Lib\site-packages\instructor\patch.py", line 161, in new_create_async
    response = await retry_async(
               ^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "D:\python313\Lib\site-packages\instructor\retry.py", line 248, in retry_async
    raise InstructorRetryException(
    ...<9 lines>...
    ) from e
instructor.exceptions.InstructorRetryException: 1 validation error for TEditRelationList
  Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/json_invalid

**Comment by shuaidaming** [comment]
how can allow

> Building... [upserting graphs]: 14%|█▍ | 1/7 [07:18<43:53, 438.84s/it]
> 
> Error during insertion: 1 validation error for TEditRelationList Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str] For further information visit https://errors.pydantic.dev/2.10/v/json_invalid Traceback (most recent call last): File "D:\python313\Lib\site-packages\instructor\retry.py", line 245, in retry_async raise e File "D:\python313\Lib\site-packages\instructor\retry.py", line 228, in retry_async return await process_response_async( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<6 lines>... ) ^ File "D:\python313\Lib\site-packages\instructor\process_response.py", line 82, in process_response_async model = response_model.from_response( response, ...<2 lines>... mode=mode, ) File "D:\python313\Lib\site-packages\instructor\function_calls.py", line 166, in from_response return cls.parse_json(completion, validation_context, strict) ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\instructor\function_calls.py", line 384, in parse_json return cls.model_validate_json( ~~~~~~~~~~~~~~~~~~~~~~~^ message, ^^^^^^^^ context=validation_context, ^^^^^^^^^^^^^^^^^^^^^^^^^^^ strict=strict, ^^^^^^^^^^^^^^ ) ^ File "D:\python313\Lib\site-packages\pydantic\main.py", line 656, in model_validate_json return cls.**pydantic_validator**.validate_json(json_data, strict=strict, context=context) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pydantic_core._pydantic_core.ValidationError: 1 validation error for TEditRelationList Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str] For further information visit https://errors.pydantic.dev/2.10/v/json_invalid
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\python313\Lib\site-packages\instructor\retry.py", line 217, in retry_async async for attempt in max_retries: ...<27 lines>... raise e File "D:\python313\Lib\site-packages\tenacity\asyncio__init__.py", line 166, in **anext** do = await self.iter(retry_state=self._retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\tenacity\asyncio__init__.py", line 153, in iter result = await action(retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\tenacity_utils.py", line 99, in inner return call(*args, **kwargs) File "D:\python313\Lib\site-packages\tenacity__init__.py", line 419, in exc_check raise retry_exc from fut.exception() tenacity.RetryError: RetryError[<Future at 0x14932d475d0 state=finished raised ValidationError>]
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\ma_fir\solution_final\2，graphrag推搜.py", line 41, in grag.insert( ~~~~~~~~~~~^ b1_z_cont, ^^^^^^^^^^ metadata=b1_z_id, ^^^^^^^^^^^^^^^^^ ) ^ File "D:\python313\Lib\site-packages\fast_graphrag_graphrag.py", line 75, in insert return get_event_loop().run_until_complete(self.async_insert(content, metadata, params, show_progress)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\asyncio\base_events.py", line 720, in run_until_complete return future.result() ~~~~~~~~~~~~~^^ File "D:\python313\Lib\site-packages\fast_graphrag_graphrag.py", line 143, in async_insert raise e File "D:\python313\Lib\site-packages\fast_graphrag_graphrag.py", line 128, in async_insert await self.state_manager.upsert( llm=self.llm_service, subgraphs=subgraphs, documents=new_chunks_per_data, show_progress=show_progress ) File "D:\python313\Lib\site-packages\fast_graphrag_services_state_manager.py", line 120, in upsert _, _ = await self.edge_upsert_policy(llm, self.graph_storage, chain(*edges)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\fast_graphrag_policies_graph_upsert.py", line 330, in **call** tasks = await asyncio.gather(*edge_upsert_tasks) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\fast_graphrag_policies_graph_upsert.py", line 223, in _upsert_edge upserted_eges, new_edges, to_delete_edges = await self._merge_similar_edges( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ llm, target, existing_edges, edges ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "D:\python313\Lib\site-packages\fast_graphrag_policies_graph_upsert.py", line 260, in _merge_similar_edges edge_grouping, _ = await format_and_send_prompt( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<8 lines>... ) ^ File "D:\python313\Lib\site-packages\fast_graphrag_llm_base.py", line 43, in format_and_send_prompt return await llm.send_message(prompt=formatted_prompt, response_model=response_model, **args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\fast_graphrag_utils.py", line 49, in wait_func result = await func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python313\Lib\site-packages\fast_graphrag_llm_llm_openai.py", line 90, in send_message llm_response: T_model = await self.llm_async_client.chat.completions.create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<7 lines>... ) ^ File "D:\python313\Lib\site-packages\instructor\client.py", line 387, in create return await self.create_fn( ^^^^^^^^^^^^^^^^^^^^^ ...<8 lines>... ) ^ File "D:\python313\Lib\site-packages\instructor\patch.py", line 161, in new_create_async response = await retry_async( ^^^^^^^^^^^^^^^^^^ ...<9 lines>... ) ^ File "D:\python313\Lib\site-packages\instructor\retry.py", line 248, in retry_async raise InstructorRetryException( ...<9 lines>... ) from e instructor.exceptions.InstructorRetryException: 1 validation error for TEditRelationList Invalid JSON: EOF while parsing a value at line 1 column 0 [type=json_invalid, input_value='', input_type=str] For further information visit https://errors.pydantic.dev/2.10/v/json_invalid

data's quantity up to 100 billion or more，once build cost is so huge，if you really want to interrupt，please save previous results ,when i rerun it ,i can remove the bad one row，then continue run after previous save，actually ，this need is necessay，for an example，last month，i have build a big graphrag base a huge history data，but this month，newly added many data，i want to add these data to  previous foundation，how i can do?

**Comment by shuaidaming** [comment]
In a word 
1，skip invalid exception and continue pipe instead of interrupt；
2，adding function --- add new data to previous foundation ,allow graphrag incremental update

**Comment by shuaidaming** [comment]
after complete these two very core function ,this will be a very great industrial frame

**Comment by shuaidaming** [comment]
i solve it

**Comment by liukidar** [comment]
Hello! Can you comment on how you managed to solve this? It could be helpful for other people who may stumble on this thread!
