### ISSUE TITLE
Wrong dimensionality of the vectors

### ISSUE THREAD

**Issue by JV-X** [circlemind-ai/fast-graphrag#55]
I am trying to run the sample code, but every time I run it to 43% of "computing embeddings", the program stops and reports an error. The error is as follows，how to resolve this bug? 

console output:
```
(base) hygx@hygx:~/code/fast-graphrag$  /usr/bin/env /home/hygx/.cache/pypoetry/virtualenvs/fast-graphrag-Ug5_5RSE-py3.10/bin/python /home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 54406 -- /home/hygx/code/fast-graphrag/snippet.py 
Extracting data: 100%|██████████████████████████| 1/1 [01:46<00:00, 106.26s/it]
Building... [computing embeddings]:  43%|███▍    | 3/7 [00:08<00:12,  3.09s/it]Error during insertion: Wrong dimensionality of the vectors
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/hygx/.vscode-server/extensions/ms-python.debugpy-2024.14.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/home/hygx/code/fast-graphrag/snippet.py", line 36, in <module>
    grag.insert(f.read())
  File "/home/hygx/code/fast-graphrag/fast_graphrag/_graphrag.py", line 75, in insert
    return get_event_loop().run_until_complete(self.async_insert(content, metadata, params, show_progress))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/hygx/code/fast-graphrag/fast_graphrag/_graphrag.py", line 143, in async_insert
    raise e
  File "/home/hygx/code/fast-graphrag/fast_graphrag/_graphrag.py", line 128, in async_insert
    await self.state_manager.upsert(
  File "/home/hygx/code/fast-graphrag/fast_graphrag/_services/_state_manager.py", line 128, in upsert
    await self.entity_storage.upsert(ids=(i for i, _ in upserted_nodes), embeddings=embeddings)
  File "/home/hygx/code/fast-graphrag/fast_graphrag/_storage/_vdb_hnswlib.py", line 65, in upsert
    self._index.add_items(data=embeddings, ids=ids, num_threads=self.config.num_threads)
RuntimeError: Wrong dimensionality of the vectors
Building... [computing embeddings]:  43%|███▍    | 3/7 [00:21<00:29,  7.28s/it]

```

my code:
```
from fast_graphrag import GraphRAG
from fast_graphrag._llm import OpenAILLMService, OpenAIEmbeddingService
import time

t1 = time.time()
DOMAIN = "Analyze this story and identify the characters. Focus on how they interact with each other, the locations they explore, and their relationships."

EXAMPLE_QUERIES = [
    "What is the significance of Christmas Eve in A Christmas Carol?",
    "How does the setting of Victorian London contribute to the story's themes?",
    "Describe the chain of events that leads to Scrooge's transformation.",
    "How does Dickens use the different spirits (Past, Present, and Future) to guide Scrooge?",
    "Why does Dickens choose to divide the story into \"staves\" rather than chapters?"
]

ENTITY_TYPES = ["Character", "Animal", "Place", "Object", "Activity", "Event"]
t2 = time.time()

grag = GraphRAG(
    working_dir="./book_example",
    domain=DOMAIN,
    example_queries="\n".join(EXAMPLE_QUERIES),
    entity_types=ENTITY_TYPES,
    config=GraphRAG.Config(
        llm_service=OpenAILLMService(model="deepseek-chat", base_url="https://api.deepseek.com/v1", api_key="sk-xxxx"),
        embedding_service=OpenAIEmbeddingService(
            model="BAAI/bge-m3",
            base_url="https://api.siliconflow.cn/v1",
            api_key="sk-xxx",
            embedding_dim=512,  # the output embedding dim of the chosen model
        )
    )
)
t3 = time.time()
with open("./book.txt") as f:
    grag.insert(f.read())
t4 = time.time()
print(grag.query("Who is Scrooge?").response)
t5 = time.time()

print(t2-t1)
print(t3-t2)
print(t4-t3)
print(t5-t4)
```

I have tried removing the embedding_dim parameter (512) passed when creating the OpenAIEmbeddingService, but I get the same error

**Comment by 21m1n** [comment]
the dimension of of BAAI/bge-m3 embedding model should be 1024 instead of 512.

**Comment by JV-X** [comment]
> the dimension of of BAAI/bge-m3 embedding model should be 1024 instead of 512.

thanks so much, it work!!
